// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_YdEjgx-bkjh_ULhYZ3_0Z4XJUfncbxo',
    appId: '1:165480202753:web:930c97ea25899c814cb600',
    messagingSenderId: '165480202753',
    projectId: 'quest-rideshare',
    authDomain: 'quest-rideshare.firebaseapp.com',
    storageBucket: 'quest-rideshare.appspot.com',
    measurementId: 'G-YFLDPZMXMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU2qEWoD7_-XqSh7pteKpf0OOLWsPPzhw',
    appId: '1:165480202753:android:0a72d52bf016dfce4cb600',
    messagingSenderId: '165480202753',
    projectId: 'quest-rideshare',
    storageBucket: 'quest-rideshare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUZ0v4DHLlt3qDvhtprL-xd39Us5q0btI',
    appId: '1:165480202753:ios:0bf10a796a3dd8c04cb600',
    messagingSenderId: '165480202753',
    projectId: 'quest-rideshare',
    storageBucket: 'quest-rideshare.appspot.com',
    iosBundleId: 'com.quest.questRideshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUZ0v4DHLlt3qDvhtprL-xd39Us5q0btI',
    appId: '1:165480202753:ios:0bf10a796a3dd8c04cb600',
    messagingSenderId: '165480202753',
    projectId: 'quest-rideshare',
    storageBucket: 'quest-rideshare.appspot.com',
    iosBundleId: 'com.quest.questRideshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_YdEjgx-bkjh_ULhYZ3_0Z4XJUfncbxo',
    appId: '1:165480202753:web:5aaf77558cced8174cb600',
    messagingSenderId: '165480202753',
    projectId: 'quest-rideshare',
    authDomain: 'quest-rideshare.firebaseapp.com',
    storageBucket: 'quest-rideshare.appspot.com',
    measurementId: 'G-F9CSFSS3TF',
  );
}
